version: "2"
services:
  app:
    container_name: app
    image: old_project:latest
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    environment: 
        - MONGODB_URI=mongodb://mongo/HelloMongoose
        
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"