version: "2"
services:
  app:
    container_name: app
    image: old_project:latest
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    environment: 
        - MONGODB_URI=mongodb://heroku_xgptbvzv:97d36m33l0mii6j6u1h6dlu49d@ds111922.mlab.com:11922/heroku_xgptbvzv

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"