apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  labels:
    name:  frontend
    type: app
spec:
  selector:
    matchLabels:
      name: frontend
  
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  replicas: 2  
  template:
    metadata:
      labels:
        name:  frontend
    spec:
    
     

      containers: 
        
      - image:  docker.pkg.github.com/kaungkhant97/demo_node_backend/front_end:latest
        imagePullPolicy: Always
        name:  backend
        ports:
          - containerPort: 3000

          
      
      imagePullSecrets:
        - name: regsecret   
      restartPolicy: Always
      