name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build node_backend --file node_backend/Dockerfile --tag backend_image:latest
    - name: Login to Github package
      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker Image
      run: docker tag backend_image:latest docker.pkg.github.com/kaungkhant97/demo_node_backend/backend_image:latest
    - name: push docker Image
      run: docker tag docker.pkg.github.com/kaungkhant97/demo_node_backend/backend_image:latest
