name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Login to Github package
      run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Backend Docker image
      run: docker build node_backend --file node_backend/Dockerfile --tag backend_image:latest
    - name: Tag Backend docker Image
      run: docker tag backend_image:latest docker.pkg.github.com/kaungkhant97/demo_node_backend/backend_image:latest
    - name: push Backend docker Image
      run: docker push docker.pkg.github.com/kaungkhant97/demo_node_backend/backend_image:latest
    - name: Build the Frontend Docker image
      run: docker build react-fetch-rest-api --file react-fetch-rest-api/Dockerfile --tag front_end:latest
    - name: Tag Frontend docker Image
      run: docker tag front_end:latest docker.pkg.github.com/kaungkhant97/demo_node_backend/front_end:latest
    - name: push Frontend docker Image
      run: docker push docker.pkg.github.com/kaungkhant97/demo_node_backend/front_end:latest
      
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:    
         kubeconfig: ${{ secrets.do_kube_config }}
        # If your kubeconfig has multiple contexts, use this field to use a specific context, otherwise the default one would be chosen
        # context: # optional, default is 
        # Cluster Url
       #  k8s-url: # optional, default is 
         # Service account secret. Run kubectl get serviceaccounts <service-account-name> -o yaml and copy the service-account-secret-name. Copy the ouptut of kubectl get secret <service-account-secret-name> -o yaml
         #k8s-secret: # optional, default is 
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            deployment_scripts/db-deploy.yaml
            deployment_scripts/backend_deploy.yaml
            deployment_scripts/backend_service.yaml
            deployment_scripts/frontend_deploy.yaml
            deployment_scripts/frontend_service.yaml
        
 
     
      
