name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: navigate
      run: cd node_backend
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backend_image:$(date +%s)
